---
# First, find out what distro our hosts are running
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution }}

- hosts:
  - Debian
  tasks:
    # Debian doesn't install python-apt and python-pycurl by default;
    # install it so we can use apt and apt_key later
    - name: install Ansible requirements
      shell: "apt-get -y install {{ item }}"
      with_items:
        - python-apt
        - python-pycurl
    # Debian doesn't install the lsb-release package by default;
    # install it so we can use ansible_lsb.codename later
    - name: Install lsb-release package
      apt: >
        name="lsb-release"
        state=present

- hosts:
  - "Ubuntu:&deploy"
  - "Debian:&deploy"
  tasks:
    - name: "install APT cache package"
      apt: >-
        name="{{ item }}"
        state=present
      with_items:
        - apt-cacher-ng
        - apache2

- hosts:
  - Ubuntu
  - Debian
  tasks:
    - name: add ceph.com package signing key
      apt_key: >
        url="https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc"
        state=present
    - name: add ceph.com package repository
      apt_repository: >
        repo="deb http://ceph.com/debian-{{ ceph_release }}/ {{ ansible_lsb.codename }} main"
        state=present
    - name: update package cache
      apt: update_cache=yes
    - name: install packages
      apt: >
        name="{{ item }}"
        state=present
      with_items:
        - ntp
        - ceph
        - ceph-deploy
    - name: enable services
      service: >-
        name="{{ item }}"
        state=started
      with_items:
        - ntp

- hosts:
  - "CentOS:&deploy"
  - "Red Hat Enterprise Linux:&deploy"
  tasks:
    - name: "install yum cache packages"
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - yum-plugin-local
        - httpd
    - name: share yum cache via HTTP
      file: >
        state=link
        src="/var/lib/yum/plugins/local"
        dest="/var/www/html/yum"
    - name: enable httpd
      service: >
        name=httpd
        state=started
        

- hosts:
  - CentOS
  - Red Hat Enterprise Linux
  tasks:
    - name: disable unnecessary yum plugins
      ini_file: >
        dest="/etc/yum/pluginconf.d/{{ item }}.conf"
        section="main"
        option="enabled"
        value="0"
      with_items:
        - fastestmirror
    - name: install redhat-lsb-core package
      yum: >
        name="redhat-lsb-core"
        state=present


- hosts:
  - CentOS
  - Red Hat Enterprise Linux
  tasks:
    - name: add package signing keys
      rpm_key: >
        key="{{ item }}"
        state=present
      with_items:
        - 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'
        - 'https://fedoraproject.org/static/0608B895.txt'
        - 'https://fedoraproject.org/static/352C64E5.txt'
    - name: add package repositories
      shell: >
        yum-config-manager --add-repo http://{{ item }}
      with_items:
        - "download.fedoraproject.org/pub/epel/{{ ansible_lsb.major_release }}/{{ ansible_architecture }}"
        - "ceph.com/rpm-{{ ceph_release }}/rhel{{ ansible_lsb.major_release }}/{{ ansible_architecture }}"
        - "ceph.com/rpm-{{ ceph_release }}/rhel{{ ansible_lsb.major_release }}/noarch"
    - name: exclude Ceph packages from EPEL
      ini_file: >
        dest="/etc/yum.repos.d/download.fedoraproject.org_pub_epel_{{ ansible_lsb.major_release }}_{{ ansible_architecture }}.repo"
        section="download.fedoraproject.org_pub_epel_{{ ansible_lsb.major_release }}_{{ ansible_architecture }}"
        option="exclude"
        value="ceph*"
    - name: install packages
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - ntp
        - ceph
        - ceph-deploy
    - name: enable services
      service: >-
        name="{{ item }}"
        state=started
      with_items:
        - ntpd
